### ISSUE TITLE
bump version to 2.2.1 when possible

### ISSUE THREAD

**Issue by moderation** [mesosphere/etcd-mesos#78]
2.2.1 was released about a week ago
https://github.com/coreos/etcd/releases/tag/v2.2.1

**Comment by jdef** [comment]
xref https://github.com/kubernetes/kubernetes/issues/16618

**Comment by jdef** [comment]
...and 2.2.1 has landed in k8s: https://github.com/kubernetes/kubernetes/pull/16694
