### ISSUE TITLE
bump mesos-go to version to include fix for cpu hogging

### ISSUE THREAD

**Issue by spacejam** [mesosphere/etcd-mesos#84]
The current included version of mesos-go will spin in the message decoder loop, consuming a cpu core without doing any work in some situations.  The current master fixes it.  We should use it.

**Comment by jdef** [comment]
fixed in master

**Comment by jdef** [comment]
xref jdef_run_job_with_timeout

**Comment by spacejam** [comment]
Awesome, thanks @jdef!
